# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03f7db711d1a53e8e631e96b5bbd9a6b1d0bd342ebeb34473950f47a816c3f1808e03054737e5ac48c5c20746fb903365272a7c689342b8e45c88e3bea1b66d8

test:
  secret_key_base: 6e7c4501524f49b1cc5bbdae0cc1b6b1454d505fc3136a518d19c1195a68eafd76c46d028b60022bc0e8870f48b06f5998442ac8de7183d630345b74d29a72c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
