Category.create(id:1, name_category:"Eletrônicos")
Category.create(id:2, name_category:"Cosméticos")
Category.create(id:3, name_category:"Brinquedos")
Category.create(id:4, name_category:"Roupas")
Category.create(id:5, name_category:"Remédios")
Category.create(id:6, name_category:"Suplementos")
